index:
  path: /
  controller: App\Controller\DefaultController::homepage

characters :
  path: /characters/{param}
  controller: App\Controller\CharacterController::list
  defaults: { param: all }


character :
  path: /character/{slug}
  controller: App\Controller\CharacterController::detail

404 :
  path : /404
  controller: App\Controller\ErrorController::error404

list-not-found-error :
  path : /errors/list-not-found
  controller : App\Controller\ErrorController::listNotFoundError